### ISSUE TITLE
client.js should be propel-client.js

### ISSUE THREAD

**Issue by petele** [GoogleChrome/Propel#32]
client is too generic, i want to know what the js files i include in my project do via their file name, client.js tells me nothing

**Comment by gauntface** [comment]
+1 totally agree.

I was considering renaming window.goog.propel.Client to window.goog.propel.PushClient as well, yay or nay to that @petele ?

**Comment by petele** [comment]
+1

**Comment by addyosmani** [comment]
`window.goog.propel.PushClient` sgtm. I was going to suggest it should be `window.goog.propel.pushClient` but it's unclear whether there are historic camel-casing rules we're trying to adhere to here. /bikeshed :)

**Comment by gauntface** [comment]
PushClient is a class that the developer needs to instantiate hence the upper case.

The reason it doesn't instantiate immediately is because it instantly starts making use of SW etc. Developers are expected to check if everything is supported with PushClient.supported() OR catch the error when they construct the object.

Happy to make changes if there is a better way to handle this.
